<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_gl_pengaturan extends CI_Model
{

    public $table = 'tb_pengaturan';
    public $id = 'id_pengaturan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
	
	function view_query_general($query)
	{
		$query = $this->db->query($query);
		if($query->num_rows() > 0)
		{
			return $query;
		}
		else
		{
			return false;
		}
	}
	
	function exec_query_general($query)
	{
		/*SIMPAN DAN CATAT QUERY*/
			$this->M_gl_log->simpan_query($query);
		/*SIMPAN DAN CATAT QUERY*/
	}
	
	function get_data_pengaturan($cari)
	{
		$query = "SELECT nilai FROM tb_pengaturan WHERE id_pengaturan = ".$cari." GROUP BY nilai;";
		$query = $this->db->query($query);
		if($query->num_rows() > 0)
		{
			return $query;
		}
		else
		{
			return false;
		}
	}

}

/* End of file M_gl_pengaturan.php */
/* Location: ./application/models/M_gl_pengaturan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-30 15:11:17 */
/* http://harviacode.com */